# Generated by Django 5.0.7 on 2024-08-03 16:08

import API.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chartdatatable',
            fields=[
                ('Rowid', models.AutoField(primary_key=True, serialize=False)),
                ('ReferenceNo', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('fathername', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('dob', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('statecode', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('districtcode', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('sector', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('emailid', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('isactive', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('createdby', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('createddate', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updatedby', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updatedon', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'chartdatatable',
            },
        ),
        migrations.CreateModel(
            name='Education_table',
            fields=[
                ('Rowid', models.AutoField(primary_key=True, serialize=False)),
                ('ReferenceNo', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('coursename', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('year', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Degree', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('institutionname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('boardname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('marks', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('createdby', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('createddate', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('updatedby', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('updatedon', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'db_table': 'education_table',
            },
        ),
        migrations.CreateModel(
            name='Pdf_table',
            fields=[
                ('Rowid', models.AutoField(primary_key=True, serialize=False)),
                ('ReferenceNo', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('dob_pdf', models.FileField(blank=True, upload_to=API.models.Pdf_table.nameFile)),
                ('address_pdf', models.FileField(blank=True, upload_to=API.models.Pdf_table.nameFile)),
                ('collage_request_letter', models.FileField(blank=True, upload_to=API.models.Pdf_table.nameFile)),
                ('createdby', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('createddate', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('updatedby', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('updatedon', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'db_table': 'pdf_table',
            },
        ),
    ]
